
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(562, 411)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 40, 501, 61))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.routeButton = QtWidgets.QPushButton(self.centralwidget)
        self.routeButton.setGeometry(QtCore.QRect(330, 270, 181, 51))
        self.routeButton.setObjectName("routeButton")
        self.quantityButton = QtWidgets.QPushButton(self.centralwidget)
        self.quantityButton.setGeometry(QtCore.QRect(330, 200, 181, 51))
        self.quantityButton.setObjectName("quantityButton")
        self.combo_Y = QtWidgets.QComboBox(self.centralwidget)
        self.combo_Y.setGeometry(QtCore.QRect(340, 160, 73, 22))
        self.combo_Y.setObjectName("combo_Y")
        self.combo_Y.addItem("")
        self.combo_Y.addItem("")
        self.combo_Y.addItem("")
        self.combo_Y.addItem("")
        self.combo_Y.addItem("")
        self.combo_Y.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 110, 251, 231))
        self.label_2.setObjectName("label_2")
        self.y_axis_label = QtWidgets.QLabel(self.centralwidget)
        self.y_axis_label.setGeometry(QtCore.QRect(350, 130, 55, 16))
        self.y_axis_label.setObjectName("y_axis_label")
        self.x_axis_label = QtWidgets.QLabel(self.centralwidget)
        self.x_axis_label.setGeometry(QtCore.QRect(430, 130, 55, 16))
        self.x_axis_label.setObjectName("x_axis_label")
        self.combo_X = QtWidgets.QComboBox(self.centralwidget)
        self.combo_X.setGeometry(QtCore.QRect(420, 160, 73, 22))
        self.combo_X.setObjectName("combo_X")
        self.combo_X.addItem("")
        self.combo_X.addItem("")
        self.combo_X.addItem("")
        self.combo_X.addItem("")
        self.combo_X.addItem("")
        self.combo_X.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 562, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "BAJA Run Analysis"))
        self.routeButton.setText(_translate("MainWindow", "Plot Route on Browser Tab"))
        self.quantityButton.setText(_translate("MainWindow", "Plot Quantity vs. Time"))
        self.combo_Y.setItemText(0, _translate("MainWindow", "Time"))
        self.combo_Y.setItemText(1, _translate("MainWindow", "RPM"))
        self.combo_Y.setItemText(2, _translate("MainWindow", "Gas"))
        self.combo_Y.setItemText(3, _translate("MainWindow", "Speed"))
        self.combo_Y.setItemText(4, _translate("MainWindow", "Latitude"))
        self.combo_Y.setItemText(5, _translate("MainWindow", "Longitude"))
        self.label_2.setText(_translate("MainWindow", "Area for the Plot"))
        self.y_axis_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Y-Axis</p></body></html>"))
        self.x_axis_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">X-Axis</p></body></html>"))
        self.combo_X.setItemText(0, _translate("MainWindow", "Time"))
        self.combo_X.setItemText(1, _translate("MainWindow", "RPM"))
        self.combo_X.setItemText(2, _translate("MainWindow", "Gas"))
        self.combo_X.setItemText(3, _translate("MainWindow", "Speed"))
        self.combo_X.setItemText(4, _translate("MainWindow", "Latitude"))
        self.combo_X.setItemText(5, _translate("MainWindow", "Longitude"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
